development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: zone-backend_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: zone-backend_production
